# Generated by Django 4.0.4 on 2022-06-07 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(default='mercedes', max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('luggage', models.CharField(max_length=20)),
                ('doors', models.CharField(max_length=10)),
                ('passengers', models.CharField(max_length=10)),
                ('transmission', models.CharField(max_length=30)),
                ('gas', models.CharField(max_length=30)),
                ('interior1', models.ImageField(upload_to='images/')),
                ('interior2', models.ImageField(upload_to='images/')),
                ('interior3', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('luggage', models.CharField(max_length=20)),
                ('doors', models.CharField(max_length=10)),
                ('passengers', models.CharField(max_length=10)),
                ('transmission', models.CharField(max_length=30)),
                ('gas', models.CharField(max_length=30)),
                ('interior1', models.ImageField(upload_to='images/')),
                ('interior2', models.ImageField(upload_to='images/')),
                ('interior3', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email adress')),
                ('username', models.CharField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('firstname', models.CharField(blank=True, max_length=120)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.newuser')),
            ],
        ),
    ]
