# Generated by Django 4.0.4 on 2022-06-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(default='mercedes', max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('luggage', models.CharField(max_length=20)),
                ('doors', models.CharField(max_length=10)),
                ('passengers', models.CharField(max_length=10)),
                ('transmission', models.CharField(max_length=30)),
                ('gas', models.CharField(max_length=30)),
                ('interior1', models.ImageField(upload_to='images/')),
                ('interior2', models.ImageField(upload_to='images/')),
                ('interior3', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('luggage', models.CharField(max_length=20)),
                ('doors', models.CharField(max_length=10)),
                ('passengers', models.CharField(max_length=10)),
                ('transmission', models.CharField(max_length=30)),
                ('gas', models.CharField(max_length=30)),
                ('interior1', models.ImageField(upload_to='images/')),
                ('interior2', models.ImageField(upload_to='images/')),
                ('interior3', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email adress')),
                ('user_name', models.CharField(max_length=120, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
