# Generated by Django 4.0.4 on 2022-05-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('luggage', models.CharField(max_length=20)),
                ('doors', models.CharField(max_length=10)),
                ('passengers', models.CharField(max_length=10)),
                ('transmission', models.CharField(max_length=30)),
                ('gas', models.CharField(max_length=30)),
                ('interior1', models.ImageField(upload_to='images/')),
                ('interior2', models.ImageField(upload_to='images/')),
                ('interior3', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
