# Generated by Django 4.0.4 on 2022-06-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_user_delete_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
